# Generated by Django 4.2.7 on 2023-11-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hometeam', models.CharField(max_length=20)),
                ('hometeamscore', models.IntegerField()),
                ('awayteam', models.CharField(max_length=20)),
                ('awayteamscore', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main_app/static/uploads/default.jpeg', upload_to='main_app/static/uploads'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('Arsenal', 'Arsenal'), ('Chelsea', 'Chelsea'), ('Liverpool', 'Liverpool'), ('Manchester Utd.', 'Manchester Utd.'), ('Manchester City', 'Manchester City'), ('Tottenham', 'Tottenham')], default='Arsenal', max_length=20),
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predhometeamscore', models.IntegerField()),
                ('predawayteamscore', models.IntegerField()),
                ('timestamp', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule')),
            ],
        ),
    ]
