# Generated by Django 4.2.7 on 2023-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_schedule_alter_profile_avatar_alter_profile_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='awayteamscore',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hometeamscore',
            field=models.IntegerField(blank=True),
        ),
    ]
