# Generated by Django 4.2.7 on 2023-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_predictions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gameweek',
            field=models.IntegerField(default=1),
        ),
    ]
