# Generated by Django 4.2.7 on 2023-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_schedule_gameweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='gameweek',
            field=models.IntegerField(default='1'),
        ),
    ]
