# Generated by Django 4.2.7 on 2023-11-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0015_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.predictions')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
