# Generated by Django 4.2.7 on 2023-11-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_predictions_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date', '-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-totalpoints']},
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
