# Generated by Django 4.2.7 on 2023-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='match_completed',
            field=models.BooleanField(default=False),
        ),
    ]
