# Generated by Django 4.2.7 on 2023-11-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('Arsenal', 'Arsenal'), ('Chelsea', 'Chelsea'), ('Liverpool', 'Liverpool'), ('Manchester Utd.', 'Manchester Utd.'), ('Manchester City', 'Manchester City'), ('Tottenham', 'Tottenham')], default='Arsenal', max_length=20, null=True),
        ),
    ]
