# Generated by Django 4.2.7 on 2023-11-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='main_app.teams'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='main_app.teams'),
        ),
    ]
